### ISSUE TITLE
Add script writing option

### ISSUE THREAD

**Issue by SebastianNeiswanger** [CreativeSolutionsGroup/forms-basecamp-connector#17]
The marketing team would like a `script writing` request option added to their form, as well as having those requests sent to the board that they will make for script writing.

DoD: The `script writing` option exists and is sent to the correct board.

**Comment by SpBills** [comment]
@awtpi314 How is this going?

**Comment by awtpi314** [comment]
I need more information and am working with Sebastian to get it.

**Comment by SebastianNeiswanger** [comment]
Closed: Contacted Maiya, and she informed me that this is no longer needed. They are going with a different method since script writing is an uncommon request.
